### ISSUE TITLE
Enhancement suggestion for pager widget: Show page title when hovering

### ISSUE THREAD

**Issue by UsuallyLogical** [uhm-coe/pager-widget#1]
When generating the URL associated with the "Previous Page" or "Next Page" button, add a "title=" attribute so that the title of the previous/next page will appear when the user hovers over the button.

**Comment by figureone** [comment]
Sounds good to me! Added above, and will be included in the next version.

**Comment by UsuallyLogical** [comment]
Awesome. Thanks for addressing both of the issues I posted today.
