### ISSUE TITLE
Appearance of page widget links 

### ISSUE THREAD

**Issue by UsuallyLogical** [uhm-coe/pager-widget#2]
When I use pager-widget, a horizontal bar appears above the links:

![image](https://user-images.githubusercontent.com/44342694/49529657-5bcab300-f86b-11e8-8b73-0fda026be27c.png)

Is there away to get rid of that bar?
BTW, earlier versions of pager-widget did not show this bar (for me anyway).

**Comment by figureone** [comment]
The widget was printing out an empty `<h2 class="widget-title"></h2>` element before the pager, and you probably have `h2` elements underlined.

We've removed the empty title element, and the change will be included in the next version: https://github.com/uhm-coe/pager-widget/commit/ed675494b70dcc9594cdf890bb255e83422e1dba
