### ISSUE TITLE
Behaviour when rendered next to Posts (not Pages) in Story mode

### ISSUE THREAD

**Issue by salk31** [uhm-coe/pager-widget#3]
Hi,

Many thanks for this widget. My wife was busy trying to put buttons on the bottom of each page.

It could be our ignorance with Wordpress but we currently have your widget in the sidebar. The sidebar is also shown on Posts but always just shows "<< previous" that links to the last page.

Looking very quickly at the code it looks like it loops through and if it doesn't find the current page it takes the last page as the index. Would it make sense to detect that the current url is not a Page and then not render the links?

Maybe an easier way to find if the current url is a Page or a Post and do something different?

Thanks again

**Comment by figureone** [comment]
That makes sense! I think the site we originally developed this plugin for didn't have any Posts so we didn't see this case.

I will add detection to not render the widget on Posts (or other custom post types that don't have the `hierarchical` flag set), and release an updated version.
https://developer.wordpress.org/reference/functions/register_post_type/#hierarchical

**Comment by figureone** [comment]
Aloha, we've released version `1.8.2` that skips rendering the widget if it's on a nonhierarchical post type. Let us know if you run into any issues!

https://github.com/uhm-coe/pager-widget/commit/1d0c2a18f21d23fbfec7f5cebd78cf7ea0d08fac

**Comment by salk31** [comment]
Wow! Brilliant. Many thanks. I opened the plugins page, hit upgrade and fixed! Much appreciated. It is for a small charity website so we don't have a lot of time/cash to try and sort things out. Much appreciated. Sam
